(load "json.shen")

(load "test/terminal.shen")
(load "test/digit.shen")
(load "test/string.shen")
(load "test/number.shen")
(load "test/object.shen")
(load "test/array.shen")
(load "test/pair.shen")
(load "test/value.shen")
